### ISSUE TITLE
The package hasn't updated on pub.dev for a while (Incompatible with the latest stable Flutter SDK)

### ISSUE THREAD

**Issue by ellet0** [mchome/flutter_colorpicker#108]
First of all, I would like to thank you for your amazing work on this open source project, we are maintaining another open source project called [flutter_quill](https://github.com/singerdmx/flutter-quill) and we depend on [flutter_colorpicker](https://github.com/mchome/flutter_colorpicker) but it seems it it's incompatible with the latest version as developers reported, for more [info](https://github.com/singerdmx/flutter-quill/issues/1866)

A workaround is to use the following in `pubspec.yaml` file:

```yaml

dependency_overrides:
  flutter_colorpicker:
    git: https://github.com/mchome/flutter_colorpicker.git

```

We would like to see the new changes published on pub.dev, thank you once again.
