### ISSUE TITLE
iPhone 5s Landscape Material Dialog too large

### ISSUE THREAD

**Issue by zurie** [mchome/flutter_colorpicker#8]
If you run iPhone 5s in Landscape and pop the Material Dialog from your example, the height is too large and causes horizontal and vertical scrolling.  Since these are just empty strips of color there is no reason that it can't be sized to properly fit without additional horizontal scrolling.

**Comment by mchome** [comment]
Try commit `0d9f8cac0900234b05d75727daef53d4d639be26`.

**Comment by zurie** [comment]
Works for me! 👍   

On a side note.... how do i load specific commits ? is that with the pub.yaml file?   I ended up just copying and pasting over the material_picker.dart in my hosted packages but I wouldn't mind knowing if there was a way to target a commit rather than a version.  

Thanks!

**Comment by mchome** [comment]
ref: https://www.dartlang.org/tools/pub/dependencies#git-packages
```yml
dependencies:
  flutter_colorpicker:
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
      ref: 0d9f8cac0900234b05d75727daef53d4d639be26
```
If you feel this commit works for you, i will release new version very soon.
